#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width        0
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

mons=$($HOME/.config/bspwm/checkdual.sh)

echo $mons >> $HOME/.config/bspwm/output.txt


if [ $mons == 1 ] ; then
	bspc monitor eDP1 -d 1 2 3 4 5 6
	echo "FUCK" >> $HOME/.config/bspwm/output.txt
else
	# xrandr --output eDP1 --auto --output DP1 --auto --left-of eDP1
	xrandr --output HDMI2 --auto --output eDP1 --auto --left-of HDMI2
	bspc monitor eDP1 -d I II III
	bspc monitor HDMI2 -d IV V VI
	# bspc monitor DP1 -d 1 2 3
	echo "NO FUCK" >> $HOME/.config/bspwm/output.txt
fi
$HOME/.config/polybar/launch.sh 
